### ISSUE TITLE
Incorrectly identifies CSS Custom Properties as an error

### ISSUE THREAD

**Issue by MadeByMike** [alecthomas/chroma#102]
The following code is not highlighted correctly

```css
:root {
  --variable-name: "should be valid";
}
```
