### ISSUE TITLE
Allow user defined CSS styles for HTML output.

### ISSUE THREAD

**Issue by r10r** [alecthomas/chroma#204]
I want to apply the following style to the HTML output.  
(e.g to style line anchor links, which I've implemented in #203 )

```css
.lnt {
        text-decoration: none;
}
:focus.lnt {
        font-weight: bold;
        color: red !important;
        outline-style: none;
}
```
An option to add custom CSS styles to the HTML output would be nice.
