### ISSUE TITLE
YAML multi-line strings inconsistencies

### ISSUE THREAD

**Issue by ItalyPaleAle** [alecthomas/chroma#475]
In recent updates to Chroma, yaml multi-line strings (starting with `|`) seem to be rendered inconsistently.

Example:

```yaml
steps:

  # Sets FOO to be "some value" in the script and the next ones
  - bash: |
      FOO="some value"
      echo "##vso[task.setvariable variable=FOO]$FOO"

  # Using the $() syntax, the value is replaced inside Azure Pipelines before being submitted to the script task
  - bash: |
      echo "$(FOO)"

  # The same variable is also present as environmental variable in scripts; here the variable expansion happens within bash
  - bash: |
      echo "$FOO"
```

This renders as:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/43508/116010054-af233480-a5d1-11eb-86a4-804b29cda378.png">

As you can see, if there's a single line in the multiline string, the number of spaces at the beginning is increased (to match the | character's position). The color is also different.
Adding more than one line with the same indentation (even if empty), fixes that.

While the resulting, rendered YAML is valid, it looks odd
