### ISSUE TITLE
Wrap code lines in spans; style default line numbers using CSS :before

### ISSUE THREAD

**Issue by jaredpetersen** [alecthomas/chroma#549]
**What problem does this feature solve?**

I use Chrome via Hugo and it would be really nice to print web pages that have long lines of code while still maintaining with line number support.

By default, long lines run off the page in print mode because it's assumed that you have an infinite ability to horizontally scroll. You can correct this with a quick CSS patch, so no big deal:

```css
/* Get rid of line numbers for print */
@media print {
    pre {
        white-space: pre-wrap;
        word-wrap: break-word;
    }
}
```

With `LineNumbersInTable()` configured, the line numbers absolutely do not line up for these wrapped, long lines:

<img width="1107" alt="Screen Shot 2021-09-17 at 11 09 02 PM" src="https://user-images.githubusercontent.com/8802128/133879074-df782fd8-5a0f-43f4-b73b-6a62d36fb017.png">

If you go with the default behavior, wrapping works perfectly for the printed page:

<img width="1215" alt="Screen Shot 2021-09-17 at 11 57 03 PM" src="https://user-images.githubusercontent.com/8802128/133879654-73acd7ee-302e-4821-9915-1eb3c06e3706.png">

However, we have a new problem with the default behavior: the generated line numbers are explicitly put into the code block as content. As a result, any time you attempt to copy and past code from a webpage in screen mode, you're going to copy the line numbers which is incredibly annoying and absolutely not desirable.

**What feature do you propose?**

I propose that Chroma add a new configuration function `LinesInSpan()` that would wrap every line in the `code` block inside a `span` tag.

Users could then put in their own CSS to add line numbers using `:before` and CSS counters. That, or another function `LineNumbersBeforeSpan()` could come into play to add those CSS classes.

I can just imagine that putting line numbers in spans would be useful for other things like alternating line background colors and adding a vertical rule after the line number. That's why I'm proposing that they be separate functions.

You can see an example of someone doing this in this StackOverflow post:

https://stackoverflow.com/q/40842277/7583677

The counter from the `:before` style isn't selectable because it's not content so you don't have to worry about people copying it on accident. This solves the big problem with the current approach today.

[React Syntax Highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) + [Highlight.js](https://github.com/highlightjs/highlight.js) has this figured out already and from what I can tell, the JavaScript aspects are just generating the HTML and CSS rather than interacting with it. I have an [open source code printing utility](https://jaredpetersen.github.io/codeprinter/) that uses these two projects and the produced HTML can possibly be used as a reference.

Here's some screenshots of Chrome Dev Tools opened up to the code blocks and styling:

<img width="1774" alt="Screen Shot 2021-09-17 at 11 44 59 PM" src="https://user-images.githubusercontent.com/8802128/133879222-6d3359e6-f450-4d75-bf99-2198b7ea4e3a.png">

<img width="1774" alt="Screen Shot 2021-09-17 at 11 44 33 PM" src="https://user-images.githubusercontent.com/8802128/133879224-08179391-79e7-4e31-9f82-263eedbd743c.png">

Here's what a long line of code looks wrapped when you have this styling scheme:

<img width="1215" alt="Screen Shot 2021-09-17 at 11 50 05 PM" src="https://user-images.githubusercontent.com/8802128/133879350-a5267f68-373b-42e5-aaed-b08bf89ff52f.png">

Switching to line-based spans also allows you to add other styling as well like a vertical ruler after the lines of code (`border-left: 1px solid black;`):

<img width="1215" alt="Screen Shot 2021-09-17 at 11 50 14 PM" src="https://user-images.githubusercontent.com/8802128/133879368-0794b6f5-5860-4946-9202-259a2b266e19.png">

**Comment by jaredpetersen** [comment]
It looks like you can prevent user selection with the default generated code with some additional styling:

```css
/* LineNumbers */ 
.chroma .ln {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
    margin-right: 0.4em;
    padding: 0 0.4em 0 0.4em;
    color: #7f7f7f;
}
```

https://stackoverflow.com/q/924916/7583677

You can then add `border-right: 1px solid black;` for the vertical ruling, but it's not quite right because the line numbers are content.

<img width="1215" alt="Screen Shot 2021-09-18 at 12 40 57 AM" src="https://user-images.githubusercontent.com/8802128/133880850-2e0be727-e6f0-4f90-89f7-56a5168823c3.png">

Semantically, it still makes sense to wrap lines in spans and use CSS :before for line number styling since line numbers are not code. And again, it opens up some new options for styling.

**Comment by alecthomas** [comment]
This seems related to #373

**Comment by itsjohncs** [comment]
I wanted the line numbers to behave on small screens and wanted to get past the wrapping problem shown in your picture:

> [...] but it's not quite right because the line numbers are content.
> 
> <img alt="Screen Shot 2021-09-18 at 12 40 57 AM" width="1215" src="https://user-images.githubusercontent.com/8802128/133880850-2e0be727-e6f0-4f90-89f7-56a5168823c3.png">

A workaround is to create a gutter and then shift the line numbers into it using a negative margin. The gutter has to be a fixed size which isn't ideal, but as long as you don't have huge snippets you can just size you gutter to handle 2-3 digits. Here's an example:

```css
.highlight code {
    white-space: pre-wrap;
}

.highlight {
    padding-left: 3em;
}

.highlight .ln  {
    margin-left: -3em;
}
```
