### ISSUE TITLE
LineHighlight not working properly with horizontal overflow

### ISSUE THREAD

**Issue by tomleb** [alecthomas/chroma#558]
**Describe the bug**

Hi,

I am using chroma through hugo to display code blocks on my blog. 
One issue I'm currently having is that the lines are not fully highlighted when `overflow-x: scroll` is configured.

Here's the comparison between desktop size and mobile size. On the mobile screenshot, I have scrolled a little bit to the right so you can see that the highlighting is not going completely to the end of the code block.

**Desktop**

![Desktop](https://user-images.githubusercontent.com/7152146/135733179-5c2b4774-eddb-41fe-b490-e10f4c666599.png)

**Mobile**

![Mobile](https://user-images.githubusercontent.com/7152146/135733156-c6920817-cd2b-4b03-a657-a8df12fd77c6.png)

**To Reproduce**

1. Download this html page: https://paste.sr.ht/blob/835e85e36b57840f880e59696e17267babb9ad15 (It contains a simple code block + syntax highlighting from chroma (although I've changed the colors, but that's not important).
2. Open in browser
3. Make the window small (or use whatever browser feature to simulate small devices)
4. See that the line is highlighted only for the viewport width, but not the full overflowed width

I've been trying to find a fix for this but haven't been able to yet.. If someone with good CSS skills could help that'd be great.

The fix should probably be integrated to https://github.com/alecthomas/chroma/blob/master/formatters/html/html.go#L412 so that everyone benefits.

I've tried with `width: max-content` but that's not quite what I want.

**Comment by CIAvash** [comment]
Setting `display` property of `pre` to `grid` seems to fix the issue.
```css
pre {
    display: grid;
}

**Comment by CIAvash** [comment]
Another solution:
```css
code {
    display: inline-block;
    width: 100%;
    min-width: max-content;
}
```

**Comment by CIAvash** [comment]
Hey @tomleb,
> almost works correctly, except it's missing the right padding once scrolled fully.

That can be fixed by moving the padding of `pre` to `code` and calculating the `width`, taking into account the padding:
```css
code {
    display: inline-block;
    min-width: max-content;
    padding: var(--spacing-25);
    width: calc(100% - 2 * var(--spacing-25));
}
```

Another solution is moving the `overflow-x: auto` from `pre` to `.highlight` and adding `min-width` to `pre`, making `.highlight` auto-scroll:
```css
.highlight {
    overflow-x: auto;
}

pre {
    padding: var(--spacing-25);
    min-width: max-content;
}
```

> I wonder, would there be a way to fix it at the style-level instead, directly from chroma's style generation?

I'm not familiar with those parts, @alecthomas would know.

**Comment by CIAvash** [comment]
> and calculating the width, taking into account the padding

Actually, there is no need for that, code can be:
```css
code {
    padding: var(--spacing-25);
    display: block;
    min-width: max-content;
}
```
