### ISSUE TITLE
Theme `github` does not imitate GitHub's rendering for YAML

### ISSUE THREAD

**Issue by concretevitamin** [alecthomas/chroma#792]
**Describe the bug**

Thanks for the amazing tool!

At https://github.com/skypilot-org/skypilot/tree/master#skypilot-in-1-minute I have a `yaml` codeblock:
```yaml
resources:
  accelerators: V100:1  # 1x NVIDIA V100 GPU

num_nodes: 1  # Number of VMs to launch

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: ~/torch_examples

# Commands to be run before executing the job.
# Typical use: pip install -r requirements.txt, git clone, etc.
setup: |
  pip install torch torchvision

# Commands to run as a job.
# Typical use: launch the main program.
run: |
  cd mnist
  python main.py --epochs 1  
```

GitHub renders it like this:
<img width="896" alt="Screen Shot 2023-05-29 at 11 02 02" src="https://github.com/alecthomas/chroma/assets/592670/5c3a1f28-0994-448a-802a-bc054920282b">

I tried to imitate it in Hugo (Papermod theme):
```
 » cat assets/css/extended/theme-vars-override.css
/* https://discourse.gohugo.io/t/different-syntax-highlighting-styles-for-light-and-dark-theme/38448/8 */
/* https://github.com/adityatelange/hugo-PaperMod/discussions/645 */
:root {
    --hljs-bg: #F6F8FA;  /* GitHub */
}
```
then
```
hugo gen chromastyles --style github  > assets/css/extended/syntax.css
```
but the result looks like
<img width="770" alt="Screen Shot 2023-05-29 at 11 10 55" src="https://github.com/alecthomas/chroma/assets/592670/7973929b-09ec-4d0e-bf4f-8413ca418382">

**There are two issues here:**

1. Under the `setup` field, the indentation and highlighting are wrong.  Is there special logic for 1-line multiline strings?
2. The `github` theme does not imitate GitHub's rendering for YAML. Is there any other theme that closely imitates the latter? Can't find it after looking through the gallery.

---

**To Reproduce**

https://swapoff.org/chroma/playground/#eyJsYW5ndWFnZSI6IllBTUwiLCJzdHlsZSI6ImdpdGh1YiIsInRleHQiOiJyZXNvdXJjZXM6XG4gIGFjY2VsZXJhdG9yczogVjEwMDoxICAjIDF4IE5WSURJQSBWMTAwIEdQVVxuXG5udW1fbm9kZXM6IDEgICMgTnVtYmVyIG9mIFZNcyB0byBsYXVuY2hcblxuIyBXb3JraW5nIGRpcmVjdG9yeSAob3B0aW9uYWwpIGNvbnRhaW5pbmcgdGhlIHByb2plY3QgY29kZWJhc2UuXG4jIEl0cyBjb250ZW50cyBhcmUgc3luY2VkIHRvIH4vc2t5X3dvcmtkaXIvIG9uIHRoZSBjbHVzdGVyLlxud29ya2Rpcjogfi90b3JjaF9leGFtcGxlc1xuXG4jIENvbW1hbmRzIHRvIGJlIHJ1biBiZWZvcmUgZXhlY3V0aW5nIHRoZSBqb2IuXG4jIFR5cGljYWwgdXNlOiBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0LCBnaXQgY2xvbmUsIGV0Yy5cbnNldHVwOiB8XG4gIHBpcCBpbnN0YWxsIHRvcmNoIHRvcmNodmlzaW9uXG5cbiMgQ29tbWFuZHMgdG8gcnVuIGFzIGEgam9iLlxuIyBUeXBpY2FsIHVzZTogbGF1bmNoIHRoZSBtYWluIHByb2dyYW0uXG5ydW46IHxcbiAgY2QgbW5pc3RcbiAgcHl0aG9uIG1haW4ucHkgLS1lcG9jaHMgMSAgIiwiY2xhc3NlcyI6ZmFsc2V9
* This does not have issue 1 above, weirdly
* It does have issue 2
