### ISSUE TITLE
Chroma generates bad css which fails linting and breaks browsers.

### ISSUE THREAD

**Issue by denisbrodbeck** [alecthomas/chroma#98]
As already mentioned in [hugo issue 3914](https://github.com/gohugoio/hugo/issues/3914#issuecomment-345403132), chroma produces badly formatted / broken css code.

This happens both for:

* inline code block generation
* creation of css classes

Example output (css classes):

```css
/* LineTableTD */ .chroma .lntd { ; vertical-align: top; padding: 0; margin: 0; border: 0; }
/* LineTable */ .chroma .lntable { ; border-spacing: 0; padding: 0; margin: 0; border: 0; width: 100%; overflow: auto; display: block; }
/* LineHighlight */ .chroma .hl { background-color: #ffffcc; display: block; width: 100% }
/* LineNumbersTable */ .chroma .lnt { ; margin-right: 0.4em; padding: 0 0.4em 0 0.4em; display: block; }
/* LineNumbers */ .chroma .ln { ; margin-right: 0.4em; padding: 0 0.4em 0 0.4em; }
```

Expected output:

```css
/* LineTableTD */ .chroma .lntd { vertical-align: top; padding: 0; margin: 0; border: 0; }
/* LineTable */ .chroma .lntable { border-spacing: 0; padding: 0; margin: 0; border: 0; width: 100%; overflow: auto; display: block; }
/* LineHighlight */ .chroma .hl { background-color: #ffffcc; display: block; width: 100% }
/* LineNumbersTable */ .chroma .lnt { margin-right: 0.4em; padding: 0 0.4em 0 0.4em; display: block; }
/* LineNumbers */ .chroma .ln { margin-right: 0.4em; padding: 0 0.4em 0 0.4em; }
```

Example app:

```golang
package main

import (
	"os"
	"github.com/alecthomas/chroma/formatters/html"
	"github.com/alecthomas/chroma/styles"
)

func main() {
	builder := styles.Get("github").Builder()
	style, err := builder.Build()
	if err != nil {
		panic(err)
	}
	formatter := html.New(html.WithClasses())
	formatter.WriteCSS(os.Stdout, style)
}
```
